# Generated by Django 4.2.4 on 2023-09-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('seats', models.IntegerField()),
                ('image', models.ImageField(upload_to='cars')),
                ('features', models.CharField(max_length=500)),
                ('rent', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='Petrol', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.carlist'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
