# Generated by Django 4.2.4 on 2023-09-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_orders_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('pickad', models.CharField(max_length=500)),
                ('dropad', models.CharField(max_length=500)),
                ('picktym', models.TimeField()),
                ('droptym', models.TimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.orders')),
            ],
        ),
    ]
